/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uts;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class Nilai extends javax.swing.JFrame {
    DefaultTableModel model;
    int indek_baris;
    /**
     * Creates new form Nilai
     */
    public Nilai() {
        initComponents();
        Object[] kolom = {"No","Nama Lengkap","Bahasa inggris","bahasa indonesia","Biologi","kimia","fisika","matematika","sejarah","ekonomi","sosiologi","rata rata"};
        model = new  DefaultTableModel(kolom, 0){
            public boolean isCellEdittable(int row, int column){
                return false;
            }
        };
        jTable1.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        txtbing = new javax.swing.JTextField();
        txtindo = new javax.swing.JTextField();
        txtbio = new javax.swing.JTextField();
        txtkim = new javax.swing.JTextField();
        txtfis = new javax.swing.JTextField();
        txtmat = new javax.swing.JTextField();
        txtsej = new javax.swing.JTextField();
        txteko = new javax.swing.JTextField();
        txtsosio = new javax.swing.JTextField();
        txthasil = new javax.swing.JTextField();
        btnhitung = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnubah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("nama");

        jLabel2.setText("bahasa inggris");

        jLabel3.setText("bahasa indonesia");

        jLabel4.setText("biologi");

        jLabel5.setText("kimia");

        jLabel6.setText("fisika");

        jLabel7.setText("matematika");

        jLabel8.setText("sejarah");

        jLabel9.setText("ekonomi");

        jLabel10.setText("sosiologi");

        jLabel11.setText("Nilai rata-rata");

        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });

        txtbing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbingActionPerformed(evt);
            }
        });

        txtindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtindoActionPerformed(evt);
            }
        });

        txtbio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbioActionPerformed(evt);
            }
        });

        txtkim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkimActionPerformed(evt);
            }
        });

        txtfis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfisActionPerformed(evt);
            }
        });

        txtmat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmatActionPerformed(evt);
            }
        });

        txtsej.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsejActionPerformed(evt);
            }
        });

        txteko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtekoActionPerformed(evt);
            }
        });

        txtsosio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsosioActionPerformed(evt);
            }
        });

        txthasil.setEnabled(false);
        txthasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthasilActionPerformed(evt);
            }
        });

        btnhitung.setText("hitung");
        btnhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhitungActionPerformed(evt);
            }
        });

        btnsimpan.setText("simpan");
        btnsimpan.setEnabled(false);
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnhapus.setText("hapus");
        btnhapus.setEnabled(false);
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnubah.setText("ubah");
        btnubah.setEnabled(false);
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txthasil, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnhitung)
                                .addGap(18, 18, 18)
                                .addComponent(btnsimpan)
                                .addGap(18, 18, 18)
                                .addComponent(btnhapus)
                                .addGap(18, 18, 18)
                                .addComponent(btnubah))
                            .addComponent(txtsosio, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txteko, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsej, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmat, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfis, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtkim, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtbio, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtindo, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtbing, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtbing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtindo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtbio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtkim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtfis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtmat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtsej, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txteko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txtsosio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txthasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnhitung)
                        .addComponent(btnsimpan)
                        .addComponent(btnhapus)
                        .addComponent(btnubah)))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void txtbingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbingActionPerformed

    private void txtindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtindoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtindoActionPerformed

    private void txtbioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbioActionPerformed

    private void txtkimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkimActionPerformed

    private void txtfisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfisActionPerformed

    private void txtmatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmatActionPerformed

    private void txtsejActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsejActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsejActionPerformed

    private void txtekoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtekoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtekoActionPerformed

    private void txtsosioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsosioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsosioActionPerformed

    private void txthasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthasilActionPerformed

    private void btnhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhitungActionPerformed
        // TODO add your handling code here:
        String nama = txtnama.getText();
        String bing = txtbing.getText();
        String indo = txtindo.getText();
        String bio = txtbio.getText();
        String kim = txtkim.getText();
        String fis = txtfis.getText();
        String mat = txtmat.getText();
        String sej = txtsej.getText();
        String eko = txteko.getText();
        String sosio = txtsosio.getText();
//        String ratarata = txthasil.getText();
        
         if (nama.isEmpty()) {
            JOptionPane.showMessageDialog(this, "nama harus diisi!");
            txtnama.requestFocus();
            return;
        } else if (bing.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nilai harus diisi!");
            txtbing.requestFocus();
            return;
        } else if (indo.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nilai harus diisi!");
            txtindo.requestFocus();
            return;
        }else if (bio.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nilai harus diisi!");
            txtbio.requestFocus();
            return;
        }else if (kim.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nilai harus diisi!");
            txtkim.requestFocus();
            return;
        }else if (fis.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nilai harus diisi!");
            txtfis.requestFocus();
            return;
        }else if (mat.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nilai harus diisi!");
            txtmat.requestFocus();
            return;
        }else if (sej.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nilai harus diisi!");
            txtsej.requestFocus();
            return;
        }else if (eko.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nilai harus diisi!");
            txteko.requestFocus();
            return;
        }else if (sosio.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nilai harus diisi!");
            txtsosio.requestFocus();
            return;
        }else {
        double binggris = Double.valueOf(bing);
        double indonesia = Double.valueOf(indo);
        double biologi = Double.valueOf(bio);
        double kimia = Double.valueOf(kim);
        double fisika = Double.valueOf(fis);
        double matematika = Double.valueOf(mat);
        double sejarah = Double.valueOf(sej);
        double ekonomi = Double.valueOf(eko);
        double sosiologi = Double.valueOf(sosio);
        double rata = uts.rata(binggris, indonesia, biologi, kimia, fisika, matematika, sejarah, ekonomi, sosiologi);
        txthasil.setText(" "+rata);
        }
         
        btnhitung.setEnabled(false);
        btnsimpan.setEnabled(true);
        btnhapus.setEnabled(false);
        btnubah.setEnabled(false);
        txthasil.setEnabled(true);
        
    }//GEN-LAST:event_btnhitungActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        int No = jTable1.getRowCount()==0 ? 1: jTable1.getRowCount()+1;
        String nama = txtnama.getText();
        String bing = txtbing.getText();
        String indo = txtindo.getText();
        String bio = txtbio.getText();
        String kim = txtkim.getText();
        String fis = txtfis.getText();
        String mat = txtmat.getText();
        String sej = txtsej.getText();
        String eko = txteko.getText();
        String sosio = txtsosio.getText();
        String ratarata = txthasil.getText();
        
         if (nama.isEmpty()) {
            JOptionPane.showMessageDialog(this, "nama harus diisi!");
            txtnama.requestFocus();
        } else if (bing.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nilai harus diisi!");
            txtbing.requestFocus();
        } else if (indo.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nilai harus diisi!");
            txtindo.requestFocus();
        }else if (bio.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nilai harus diisi!");
            txtbio.requestFocus();
        }else if (kim.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nilai harus diisi!");
            txtkim.requestFocus();
        }else if (fis.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nilai harus diisi!");
            txtfis.requestFocus();
        }else if (mat.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nilai harus diisi!");
            txtmat.requestFocus();
        }else if (sej.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nilai harus diisi!");
            txtsej.requestFocus();
        }else if (eko.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nilai harus diisi!");
            txteko.requestFocus();
        }else if (sosio.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nilai harus diisi!");
            txtsosio.requestFocus();
        }else{
            Object[] data = {No, nama,bing,indo,bio,kim,fis,mat,sej,eko,sosio,ratarata};
            model.addRow(data);
            refresh();
        }
        btnhitung.setEnabled(true);
        btnsimpan.setEnabled(false);
        btnhapus.setEnabled(false);
        btnubah.setEnabled(false);
        txthasil.setEnabled(false);
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        int pilihan = JOptionPane.showConfirmDialog(this, ""
            +"Apakah anda yakin ingin menghapus data ini?", "konfirmasi",
            JOptionPane.YES_NO_CANCEL_OPTION);
        if (pilihan ==0) {
            model.removeRow(indek_baris);
            refresh();
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int r = jTable1.getSelectedRow();
        if (r != -1){
            int no = Integer.parseInt(jTable1.getValueAt(r, 0).toString());
            String nama = jTable1.getValueAt(r, 1).toString();
            String bing = jTable1.getValueAt(r, 2).toString();
            String indo = jTable1.getValueAt(r, 3).toString();
            String bio = jTable1.getValueAt(r, 4).toString();
            String kim = jTable1.getValueAt(r, 5).toString();
            String fis = jTable1.getValueAt(r, 6).toString();
            String mat = jTable1.getValueAt(r, 7).toString();
            String sej = jTable1.getValueAt(r, 8).toString();
            String eko = jTable1.getValueAt(r, 9).toString();
            String sosio = jTable1.getValueAt(r, 10).toString();
            String ratarata = jTable1.getValueAt(r, 11).toString();
            
            txtnama.setText(nama);
            txtbing.setText(bing);
            txtindo.setText(indo);
            txtbio.setText(bio);
            txtkim.setText(kim);
            txtfis.setText(fis);
            txtmat.setText(mat);
            txtsej.setText(sej);
            txteko.setText(eko);
            txtsosio.setText(sosio);
            
            btnhitung.setEnabled(false);
            btnsimpan.setEnabled(false);
            btnhapus.setEnabled(true);
            btnubah.setEnabled(true);
            txthasil.setEnabled(false);
            
            indek_baris = r;
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
        // TODO add your handling code here:
        int No = jTable1.getRowCount()==0 ? 1: jTable1.getRowCount()+1;
        String nama = txtnama.getText();
        String bing = txtbing.getText();
        String indo = txtindo.getText();
        String bio = txtbio.getText();
        String kim = txtkim.getText();
        String fis = txtfis.getText();
        String mat = txtmat.getText();
        String sej = txtsej.getText();
        String eko = txteko.getText();
        String sosio = txtsosio.getText();
        String ratarata = txthasil.getText();
       
        
        if (nama.isEmpty()) {
            JOptionPane.showMessageDialog(this, "nama harus diisi!");
            txtnama.requestFocus();
        } else if (bing.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nilai harus diisi!");
            txtbing.requestFocus();
        } else if (indo.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nilai harus diisi!");
            txtindo.requestFocus();
        }else if (bio.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nilai harus diisi!");
            txtbio.requestFocus();
        }else if (kim.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nilai harus diisi!");
            txtkim.requestFocus();
        }else if (fis.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nilai harus diisi!");
            txtfis.requestFocus();
        }else if (mat.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nilai harus diisi!");
            txtmat.requestFocus();
        }else if (sej.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nilai harus diisi!");
            txtsej.requestFocus();
        }else if (eko.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nilai harus diisi!");
            txteko.requestFocus();
        }else if (sosio.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nilai harus diisi!");
            txtsosio.requestFocus();
        }else{
            jTable1.setValueAt(nama, indek_baris, 1);
            jTable1.setValueAt(bing, indek_baris, 2);
            jTable1.setValueAt(indo, indek_baris, 3);
            jTable1.setValueAt(bio, indek_baris, 4);
            jTable1.setValueAt(kim, indek_baris, 5);
            jTable1.setValueAt(fis, indek_baris, 6);
            jTable1.setValueAt(mat, indek_baris, 7);
            jTable1.setValueAt(sej, indek_baris, 8);
            jTable1.setValueAt(eko, indek_baris, 9);
            jTable1.setValueAt(sosio, indek_baris, 10);
            jTable1.setValueAt(ratarata, indek_baris, 11);
            
            
            refresh();
            
        }
    }//GEN-LAST:event_btnubahActionPerformed
        
    
     private  void  refresh(){
        txtnama.setText("");
        txtbing.setText("");
        txtindo.setText("");
        txtbio.setText("");
        txtkim.setText("");
        txtfis.setText("");
        txtmat.setText("");
        txtsej.setText("");
        txteko.setText("");
        txtsosio.setText("");
        txthasil.setText("");
        btnsimpan.setEnabled(true);
        btnhitung.setEnabled(true);
        btnhapus.setEnabled(false);
        btnubah.setEnabled(false);
        jTable1.clearSelection();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nilai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnhitung;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btnubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtbing;
    private javax.swing.JTextField txtbio;
    private javax.swing.JTextField txteko;
    private javax.swing.JTextField txtfis;
    private javax.swing.JTextField txthasil;
    private javax.swing.JTextField txtindo;
    private javax.swing.JTextField txtkim;
    private javax.swing.JTextField txtmat;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtsej;
    private javax.swing.JTextField txtsosio;
    // End of variables declaration//GEN-END:variables
}
